"""add expires_at to short_links

Revision ID: d52bbc225153
Revises: a714f0611fa9
Create Date: 2026-01-09 15:04:55.330626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52bbc225153'
down_revision: Union[str, Sequence[str], None] = 'a714f0611fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_links', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_links', 'expires_at')
    # ### end Alembic commands ###
